#!/bin/bash
# install script of 9108 driver 
# created by qiaoyongkang 20130319

#VERSION=1.0.0.4

UnInstallLctDriver()
{
    echo -e -n "\nDriver UnInstalling.....\n"    
    rm -rf  /lib/udev/rules.d/26-longcheer-Datacard.rules
    rm -rf  /lib/udev/rules.d/11-longcheer-Datacard.rules
    rm -rf  /lib/udev/longcheer-cm55-ejectcd
    rm -rf  /lib/udev/longcheer-cm55-testcd
    rm -rf  /lib/udev/load_driver.sh
    rm -rf  /lib/udev/lcdoshift
    rmmod -f lc_ether
	
}

if [ `id | awk '{print $1}'` != "uid=0(root)" ]
then
    echo "You must run the process by root."
    read COMMAND
    exit
fi
UnInstallLctDriver



