# Makefile writed by Foxconn Han 
# We only need serial port driver for Micromax driver for MMX353W
# 
# 	eject message:
# 		from file ./Linux/driver/lcdoshift.c Line:44
# 		char MessageContent[LINE_DIM] = "55534243123456780000000080000606f50402527000000000000000000000";

PROJECT_DIR = ./

all clean install:
	make -C $(PROJECT_DIR)/Linux/driver $@


